pandas는 Python에서 데이터를 쉽고 효율적으로 분석하고 처리하기 위해 사용하는 대표적인 데이터 분석 라이브러리입니다. 
<br>엑셀과 비슷한 형태의 표(Tabular Data)를 다룰 수 있으며, Series와 DataFrame이라는 강력한 자료구조를 제공합니다. 
<br>CSV, Excel, SQL 등의 다양한 데이터 파일을 불러와 정렬, 필터링, 그룹화, 결측치 처리, 통계 분석 등을 간편하게 수행할 수 있으며, 대량의 데이터를 빠르게 가공할 수 있습니다.

```
# 설치
pip install pandas
# 또는
python -m pip install pandas
```

In [1]:
import pandas as pd

In [4]:
pd.__version__

'3.0.3'

# **1. Series**
Series는 Pandas에서 사용하는 가장 기본적인 1차원 데이터 구조로, 값(Value)과 인덱스(Index)가 함께 구성된 자료형입니다. 
<br>NumPy의 1차원 배열과 비슷하지만, 각 데이터에 이름표 역할을 하는 인덱스가 추가되어 데이터를 더 체계적으로 관리할 수 있습니다.

![시리즈](./images/시리즈.png)

In [6]:
idx = ['김사과', '반하나', '오렌지', '이메론', '배애리']
data = [67, 75, 90, 62, 98]

# pd.Series(데이터, 인덱스, ...)
pd.Series(data)

0    67
1    75
2    90
3    62
4    98
dtype: int64

In [7]:
ser1 = pd.Series(data, idx)
print(ser1)
print(ser1.index)
print(ser1.values)
print(type(ser1.values))

김사과    67
반하나    75
오렌지    90
이메론    62
배애리    98
dtype: int64
Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='str')
[67 75 90 62 98]
<class 'numpy.ndarray'>

### Index 객체란
Index 객체는 Series와 DataFrame에서 각 데이터의 위치를 식별하고 관리하기 위한 “이름표(Label)” 역할을 하는 자료구조입니다. 
<br>일반 리스트처럼 보이지만 단순한 데이터 저장용이 아니라, 데이터를 빠르게 검색하고 정렬하며 서로 다른 데이터끼리 매칭할 수 있도록 최적화된 Pandas 전용 객체입니다.

![인덱스 객체](./images/인덱스객체.png)

# **2. DataFrame**
데이터프레임(DataFrame)은 판다스(Pandas) 라이브러리에서 제공하는 중요하고 강력한 데이터 구조로, 2차원의 테이블 형태 데이터를 다루는 데 사용됩니다. 
<br>또한 각 요소는 인덱스(index), 열(column), 값(value)으로 구성되어 있습니다. 데이터프레임은 행과 열로 이루어져 있으며, 각 열은 다양한 데이터 타입을 가질 수 있습니다. 
<br>값은 넘파이의 ndarray 기반으로 저장됩니다.

![데이터 프레임](./images/데이터프레임.png)

In [ ]:
data = [[67, 93, 91],
        [75, 68, 96],
        [87, 81, 82],
        [62, 70, 75],
        [98, 56, 87]]


idx = ['김사과', '반하나', '오렌지', '이메론', '배애리']
col = ['국어', '영어', '수학']



# pd.DataFrame(데이터, 인덱스, 컬럼, ...)
pd.DataFrame(data)

    0   1   2
0  67  93  91
1  75  68  96
2  87  81  82
3  62  70  75
4  98  56  87

In [11]:
pd.DataFrame(data, idx)

      0   1   2
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [12]:
pd.DataFrame(data, idx, col)

     국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [14]:
df = pd.DataFrame(index=idx, columns=col, data=data)  # 순서는 달라도 크게 달라지는 건 없음
df

     국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [15]:
print(df.index)
print(df.columns)
print(df.values)

Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='str')
Index(['국어', '영어', '수학'], dtype='str')
[[67 93 91]
 [75 68 96]
 [87 81 82]
 [62 70 75]
 [98 56 87]]

In [17]:
# 딕셔너리를 사용하여 데이터프레임을 생성하기
dic = {
    '국어':[67, 75, 76, 62, 98],
    '영어':[93, 68, 81, 70, 56],
    '수학':[91, 96, 82, 75, 87]
}
df = pd.DataFrame(data=dic, index=idx)
df

     국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  76  81  82
이메론  62  70  75
배애리  98  56  87

# **3. CSV 파일 읽어오기**
CSV 파일은 Comma-Separated Values(쉼표로 구분된 값) 파일의 약자로, 데이터를 단순한 텍스트 형식으로 저장하는 데 사용되는 파일 형식입니다.

In [5]:
df = pd.read_csv('.\광고모델_브랜드평판.csv')
df

     이름          소속사 성별        생년월일        키  혈액형    브랜드평판지수
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201
4   유재석          안테나  남  1972-08-14    178cm    B  2,015,312
5   김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456
7   고윤정          MAA  여  1996-04-22    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035
11   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700
14  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761
15  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540
16  엄태구          팀호프  남  1983-11-09    181cm    O    380,064
17  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543
19  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       20 non-null     str
 1   소속사      20 non-null     str
 2   성별       20 non-null     str
 3   생년월일     20 non-null     str
 4   키        20 non-null     str
 5   혈액형      18 non-null     str
 6   브랜드평판지수  20 non-null     str
dtypes: str(7)
memory usage: 1.2 KB