# 크롤링
크롤링(Crawling)은 웹사이트의 HTML 문서나 API 데이터를 자동으로 수집하여 원하는 정보를 추출하는 기술입니다. 사람이 직접 웹페이지를 열어 뉴스, 상품 정보, 댓글, 주가, 날씨 등을 확인하는 과정을 프로그램이 대신 수행한다고 생각하면 이해하기 쉽습니다.

# Requests
Requests는 Python에서 웹 서버에 HTTP 요청을 보내고 응답을 받아오기 위해 사용하는 대표적인 라이브러리입니다. 웹 브라우저가 사이트에 접속할 때처럼 Python 코드에서도 웹페이지, 이미지, JSON 데이터 등을 서버로부터 가져올 수 있게 해주며, 웹 크롤링과 API 연동에서 가장 많이 사용되는 기본 도구 중 하나입니다. requests.get()으로 웹페이지를 요청하거나, requests.post()로 데이터를 서버에 전송할 수 있으며, 응답 결과로 HTML 코드, 이미지 데이터, 상태 코드 등을 쉽게 다룰 수 있습니다.

# BeautifulSoup
Beautiful Soup의 from bs4 import BeautifulSoup 코드는 Python에서 HTML이나 XML 문서를 쉽게 분석하고 원하는 데이터를 추출하기 위해 BeautifulSoup 클래스를 불러오는 코드입니다. 여기서 bs4는 BeautifulSoup4 라이브러리를 의미하며, 웹 크롤링에서 가장 많이 사용하는 라이브러리 중 하나입니다.


'''
즉, requests로 가져온걸 뜯어서 쓰고 싶을 때 사용
'''

In [31]:
import requests
from bs4 import BeautifulSoup

In [42]:
# 가상 서버 주소
url = "http://127.0.0.1:5500/01.html"

# 서버에 요청 보내기
response = requests.get(url)

In [43]:
# HTML 코드 가져오기
html = response.text

In [44]:
# HTML 분석
soup = BeautifulSoup(html, "html.parser")

In [45]:
# 데이터 추출
h1 = soup.find("h1").text
h1

p = soup.find("p").text
p

'파이썬 크롤링 수업입니다.'

In [46]:
# 출력
print("제목:", h1)
print("내용:", p)

제목: 안녕하세요
내용: 파이썬 크롤링 수업입니다.

👉 find()는 Beautiful Soup에서 HTML 문서 안의 특정 태그를 검색할 때 사용하는 함수입니다. 태그 이름, 클래스(class), 아이디(id) 등의 조건을 기준으로 원하는 요소를 찾을 수 있으며, 조건에 맞는 첫 번째 요소만 반환합니다. 예를 들어 find("h1")은 첫 번째 <h1> 태그를 가져오고, .text를 사용하면 태그 안의 글자만 추출할 수 있습니다.

In [47]:
url = "http://127.0.0.1:5500/02.html"

In [49]:
import requests
from bs4 import BeautifulSoup

# 가상 서버 주소
url = "http://127.0.0.1:5500/02.html"

# 서버에 요청 보내기
response = requests.get(url)

# HTML 가져오기
html = response.text

# HTML 분석
soup = BeautifulSoup(html, "html.parser")

# 부모 태그(div) 가져오기
div = soup.find("div")

# 자식 태그 가져오기
news_title = div.find("h1").text
news_content = div.find("p").text

# 출력
print("뉴스 제목:", news_title)
print("뉴스 내용:", news_content)

뉴스 제목: 뉴스 제목
뉴스 내용: 뉴스 내용

In [51]:
url = "http://127.0.0.1:5500/03.html"

# 서버 요청
response = requests.get(url)

# HTML 가져오기
html = response.text

# HTML 분석
soup = BeautifulSoup(html, "html.parser")

# 모든 a 태그 가져오기
links = soup.find_all("a")

links

In [52]:
# 링크와 글자 출력
for link in links:
    text = link.text
    href = link["href"]

    print("사이트 이름:", text)
    print("링크 주소:", href)
    print()

사이트 이름: 네이버
링크 주소: https://naver.com

사이트 이름: 구글
링크 주소: https://google.com

In [53]:
import os
from urllib.parse import urljoin

In [62]:
url = "http://127.0.0.1:5500/04.html"

response = requests.get(url)

# HTML 파싱
soup = BeautifulSoup(response.text, "html.parser")

# img 태그 찾기
img_tag = soup.find("img")

# 이미지 주소 가져오기
img_src = img_tag["src"]

In [63]:
# 상대경로 → 절대경로 변환
img_url = urljoin(url, img_src)
img_url

'http://127.0.0.1:5500/류지.jpeg'

In [64]:
# images 폴더 생성
os.makedirs("images", exist_ok=True)

In [65]:
# 이미지 다운로드
img_response = requests.get(img_url)

In [69]:
# 파일 이름 추출
# 'http://127.0.0.1:5500/류지.jpeg'
file_name = img_url.split("/")[-1]

file_name

'류지.jpeg'

In [70]:
# 저장 경로
save_path = os.path.join("images", file_name)
save_path

'images\\류지.jpeg'

### open() 함수
pen() 함수는 파일을 읽거나 저장할 때 사용하는 함수입니다. 텍스트 파일(txt), CSV, 이미지 파일 등을 열어서 데이터를 읽거나 저장할 수 있으며, 크롤링·데이터분석·AI 개발 등 거의 모든 분야에서 사용되는 매우 중요한 기능입니다.


```
파일객체 = open("파일명", "모드", encoding= "utf-8)
```
![open](./images/open.png)

In [ ]:
# 이미지 저장
with open(save_path, "wb") as file: # 시작하고 자동으로 닫아주는 함수가 with
    file.write(img_response.content)
print("이미지 저장 완료")

이미지 저장 완료

In [87]:
# 가상 서버 주소
url = "http://127.0.0.1:5500/05.html"

# 서버 요청
response = requests.get(url)

# HTML 가져오기
html = response.text
print(html)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>표</title>
  </head>
  <body>
    <table border="1">
      <tr>
        <th>이름</th>
        <th>나이</th>
      </tr>
      <tr>
        <td>김사과</td>
        <td>20</td>
      </tr>
    </table>
  <!-- Code injected by live-server -->
<script>
	// <![CDATA[  <-- For SVG support
	if ('WebSocket' in window) {
		(function () {
			function refreshCSS() {
				var sheets = [].slice.call(document.getElementsByTagName("link"));
				var head = document.getElementsByTagName("head")[0];
				for (var i = 0; i < sheets.length; ++i) {
					var elem = sheets[i];
					var parent = elem.parentElement || head;
					parent.removeChild(elem);
					var rel = elem.rel;
					if (elem.href && typeof rel != "string" || rel.length == 0 || rel.toLowerCase() == "stylesheet") {
						var url = elem.href.replace(/(&|\?)_cacheOverride=\d+/, '');
						elem.href = url + (url.indexOf('?') >= 0 ? '&' : '?') + '_cacheOverride=' + (new Date().valueOf());
					}
					parent.appendChild(elem);
				}
			}
			var protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://';
			var address = protocol + window.location.host + window.location.pathname + '/ws';
			var socket = new WebSocket(address);
			socket.onmessage = function (msg) {
				if (msg.data == 'reload') window.location.reload();
				else if (msg.data == 'refreshcss') refreshCSS();
			};
			if (sessionStorage && !sessionStorage.getItem('IsThisFirstTime_Log_From_LiveServer')) {
				console.log('Live reload enabled.');
				sessionStorage.setItem('IsThisFirstTime_Log_From_LiveServer', true);
			}
		})();
	}
	else {
		console.error('Upgrade your browser. This Browser is NOT supported WebSocket for Live-Reloading.');
	}
	// ]]>
</script>
</body>
</html>

In [81]:
# table 가져오기
table = soup.find("table")

# 제목(th) 추출
headers = table.find_all("th")

print("제목")
for header in headers:
    print(header.text)

AttributeError: 'NoneType' object has no attribute 'find_all'

In [89]:
# 내용(td) 추출
datas = table.find_all("td")

print("\n내용")
for data in datas:
    print(data.text)

AttributeError: 'NoneType' object has no attribute 'find_all'

셀 나눠서 안 돼서 아래 한 번에 실행함

In [91]:
import requests
from bs4 import BeautifulSoup

# 가상 서버 주소
url = "http://127.0.0.1:5500/05.html"

# 서버 요청
response = requests.get(url)

# HTML 가져오기
html = response.text

# HTML 분석
soup = BeautifulSoup(html, "html.parser")

# table 가져오기
table = soup.find("table")

# 제목(th) 추출
headers = table.find_all("th")

print("제목")
for header in headers:
    print(header.text)

# 내용(td) 추출
datas = table.find_all("td")

print("\n내용")
for data in datas:
    print(data.text)

제목
이름
나이

내용
김사과
20

In [79]:
# 가상 서버 주소
url = "http://127.0.0.1:5500/06.html"

# 서버 요청
response = requests.get(url)

# HTML 가져오기
html = response.text

# HTML 분석
soup = BeautifulSoup(html, "html.parser")

In [83]:
# id 선택자
title = soup.select_one("#title").text
title

'IT'

In [85]:
# class 선택자
items = soup.select(".item")
items

[<div class="item">
 <h2>노트북</h2>
 <p>150만원</p>
 </div>,
 <div class="item">
 <h2>키보드</h2>
 <p>10만원</p>
 </div>]

In [88]:
for item in items:
    name = item.select_one("h2").text
    price = item.select_one("p").text

    print("상품명:", name)
    print("가격:", price)
    print()

상품명: 노트북
가격: 150만원

상품명: 키보드
가격: 10만원

수업 중 깜짝 과제
basicenglishspeaking 75개 topic 크롤링

In [104]:
# 가상 서버 주소
url = "https://basicenglishspeaking.com/daily-english-conversation-topics/"

# 서버 요청
request = requests.get(url)

# HTML 가져오기
html = request.text

# HTML 분석
soup = BeautifulSoup(html, "html.parser")


# table 가져오기
table = soup.find('div', {'class': 'tcb-flex-row tcb--cols--3'})

# 제목(th) 추출
headers = table.find_all("a")

print("제목")
for header in headers:
    print(header.text)

# 내용(td) 추출
datas = table.find_all("td")

print("\n내용")
for data in datas:
    print(data.text)

제목
Family
Restaurant
Books
Travel
Website
Accident
Childhood memory
Favorite rooms
Presents
Historical place
Newspaper/ Magazine
A memorable event
A favorite subject
A museum
A favorite movie
A foreign country
Parties
A teacher
A friend
A hotel
A letter
Hobbies
Music
Shopping
Holiday
Animals
A practical skill
Sport
A School
Festival
Food
Household appliance
A music band
Weather
Neighbor
Natural scenery
Outdoor activities
Law
Pollution
Traffic jam
TV program
Architect/ Building
Electronic Media
Job/ Career
Competition/ contest
A garden
Hometown
Clothing
Advertisement
A project
A wedding
A Coffee shop
Culture
Transport
Politician
Communication
Business
Computer
Exercise
Goal/ ambition
Art
Fashion
Jewelry
Cosmetic
Indoor Game
Phone conversation
Learning A Second language
A Creative Person
A celebrity
A Health Problem
Technological advancements
A Landmark
Handcraft Items
Plastic Surgery
Success

내용

전체코드

In [103]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

site = 'https://basicenglishspeaking.com/daily-english-conversation-topics/'

request = requests.get(site)
soup = BeautifulSoup(request.text, 'html.parser')

div = soup.find('div', {'class': 'thrv-columns'})
links = div.find_all('a')

data = []

for i, link in enumerate(links, start=1):
    topic = link.text.strip()
    url = link.get('href')

    data.append({
        '번호': i,
        '토픽': topic,
        '링크': url
    })

df = pd.DataFrame(data)

df

,번호,토픽,링크
0,1,Family,https://basicenglishspeaking.com/family/
1,2,Restaurant,https://basicenglishspeaking.com/restaurant/
2,3,Books,https://basicenglishspeaking.com/books/
3,4,Travel,https://basicenglishspeaking.com/travel/
4,5,Website,https://basicenglishspeaking.com/website/
...,...,...,...
70,71,Technological advancements,https://basicenglishspeaking.com/technological...
71,72,A Landmark,https://basicenglishspeaking.com/a-landmark/
72,73,Handcraft Items,https://basicenglishspeaking.com/handcraft-items/
73,74,Plastic Surgery,https://basicenglishspeaking.com/plastic-surgery/
74,75,Success,https://basicenglishspeaking.com/success/

# 다음 뉴스기사 크롤링

In [105]:
def daum_news(news_id):
    url = f'https://v.daum.net/v/{news_id}'

    headers = {
        'User-Agent': 'Mozilla/5.0'
    }

    try:
        request = requests.get(url, headers = headers)

        # 요청 실패 시 에러 발생
        request.raise_for_status()

        soup = BeautifulSoup(request.text, 'html.parser')

        # 제목 가져오기
        title = soup.find('h3', {'class': 'tit_view'})

        if title:
            title = title.text.strip()
        else:
            title = '제목없음'

        
        # 본문 가져오기
        content = soup.find('div', {'class': 'article_view'})

        if content:
            content = content.text.strip()
        else:
            content = '내용없음'

        return {
            'title': title,
            'content': content
        }


    except Exception as e:
        print('에러 발생:', e)
        return None

In [106]:
# 사용 예제
news = daum_news('20260624085206643')
news

{'title': '"제법 판다 같죠?" 생후 3주 맞은 아기 판다 폭풍성장 중 [뉴시스Pic]',
 'content': '[서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지\n           \n\n [서울=뉴시스] 류현주 기자 = 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.\n생후 21일차인 지난 23일 촬영된 사진 속에서 아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해지며 제법 판다다운 모습을 보이고 있다.\n아기판다는 에버랜드 판다월드에 살고 있는 엄마 아이바오와 아빠 러바오 사이에서 태어났다. 6월 3일 오전 10시 53분에 태어난 아기 판다는 2020년 푸바오와 2023년 쌍둥이 판다 루이바오, 후이바오 등 언니들에 이어 우리나라에서 출생한 네번째 암컷 자이언트 판다다.\n생후 21일차를 맞아 이날 진행된 건강검진에서 아기 판다는 몸무게 670g을 기록하며 출생(171g) 당시보다 3주 만에 체중이 약 4배 늘어날 정도로 건강하게 자라고 있다.\n\n\n\n            [서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지\n           \n\n \n\n\n\n            [서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지\n           \n\n \n\n\n\n            [서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지\n           \n\n \n\n\n\n            [서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지\n           \n\n \n\n\n\n            [서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지\n           \n\n☞공감언론 뉴시스 ryuhj@newsis.com'}

In [107]:
print('제목:')
print(news['title'])

제목:
"제법 판다 같죠?" 생후 3주 맞은 아기 판다 폭풍성장 중 [뉴시스Pic]

In [109]:
print('\n본문:')
print(news['content'])

본문:
[서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지


 [서울=뉴시스] 류현주 기자 = 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.
생후 21일차인 지난 23일 촬영된 사진 속에서 아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해지며 제법 판다다운 모습을 보이고 있다.
아기판다는 에버랜드 판다월드에 살고 있는 엄마 아이바오와 아빠 러바오 사이에서 태어났다. 6월 3일 오전 10시 53분에 태어난 아기 판다는 2020년 푸바오와 2023년 쌍둥이 판다 루이바오, 후이바오 등 언니들에 이어 우리나라에서 출생한 네번째 암컷 자이언트 판다다.
생후 21일차를 맞아 이날 진행된 건강검진에서 아기 판다는 몸무게 670g을 기록하며 출생(171g) 당시보다 3주 만에 체중이 약 4배 늘어날 정도로 건강하게 자라고 있다.



            [서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지






            [서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지






            [서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지






            [서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지






            [서울=뉴시스] 에버랜드가 국내 세번째 자연번식으로 태어나 생후 3주째를 맞은 아기 판다 사진을 24일 공개했다.아기 판다는 다소 통통해진 몸매에 눈, 귀, 어깨, 팔, 다리 주변에 판다의 특징인 검은 무늬가 확연해졌으며 몸무게가 출생 당시(171g)보다 약 4배 증가한 670g을 기록할 정도로 건강하게 자라고 있다. (사진=에버랜드 제공) 2026.06.24. photo@newsis.com *재판매 및 DB 금지


☞공감언론 뉴시스 ryuhj@newsis.com

In [110]:
news = daum_news('20260624113500663')
news

{'title': '[르포] "채소 칸에 도마·국자라도"... 홈플러스의 처절한 빈자리 채우기',
 'content': '경기도 파주에 위치한 홈플러스 매장의 외관./김수정 기자\n           \n\n 경기도 파주에 한 홈플러스 매장. 멀리서도 시계탑 달린 커다란 5층 건물이 한눈에 들어온다. 이 지점은 2016년 개점 당시, 지역 최대 규모의 복합 쇼핑몰이라는 점을 내세우며 화려하게 문을 열었다. 주말이면 가족 단위 방문객으로 인산인해를 이루며 지역 상권의 중심지 역할을 톡톡히 해왔다. 10년이 흐른 현재, 건물의 상징이었던 시계탑은 멈춰 섰고, 사람들의 발걸음도 현저히 줄었다. \n\n\n\n            홈플러스 매장 1층 이벤트 매대 일부 공간이 텅 비어 있는 모습./김수정 기자\n           \n\n 지난 22일 오전 11시, 입구에 들어서자마자 1층 한 쪽 덩그러니 비어 있는 공간이 눈에 띄었다. \'지금까지 없던 가장 현명한 선택\'이라는 홈플러스의 슬로건이 무색하게, 현장에서 마주한 모습은 깊어지는 경영난을 고스란히 노출시켰다. \n\n\n\n            신선 식품 코너에 국자, 도마 등 식기류가 진열된 모습./김수정 기자\n           \n\n ◆상추·달걀 자리에 \'냄비와 국자\' \n홈플러스가 오프라인 경쟁력 확보를 위해 사활을 걸고 추진해 온 \'메가푸드마켓\' 식품관. 신선도가 생명인 달걀, 채소, 샐러드 등이 진열되어 있어야 할 신선 코너 냉장 매대에 뜬금없이 주방용품과 국자, 도마 등 식기류들이 줄지어 진열돼 있었다. \'텅 빈 매장\'이라는 인상을 주지 않기 위해 매대를 채우려 애쓴 현장의 간절함과 처절함이 묻어났다. 인근에 거주한다는 방문객 A씨는 "한달만에 왔는데 신선실에 냄비와 국자가 진열된 것을 보고 깜짝 놀랐다"고 말했다. \n\n\n\n            홈플러스 PB브랜드 \'Simplus\' 아메리카노가 매대 가득 진열된 모습./김수정 기자\n           \n\n 제품의 다양성도 크게 후퇴했다. 밀키트 코너는 홈플러스의 자체 브랜드(PB)인 \'심플러스(simplus)\'와 \'홈밀(homemeal)\' 제품으로만 빼곡했다. 음료 코너 냉장고에도 심플러스의 1000원 아메리카노와 복숭아 음료만 한 줄로 진열돼 있었다. 일반 라면 코너에는 특정 몇 가지 제품만 매대를 간신히 채우고 있었다. 30대 주부 B씨는 "집이 가까워 자주 왔었는데 요즘은 살 게 없어 발길이 뜸해졌다"며 "가격 메리트는 있지만, 구하기 힘든 상품도 아니고 \'불닭볶음면\' 같은 대중적인 라면조차 없다"고 아쉬워했다. \n\n\n\n            홈플러스 메가푸드마켓 내 라면 코너의 모습./김수정 기자\n           \n\n 델리(즉석식품) 코너는 6990원 치킨만이 빈자리를 메우고 있었다. 홈플러스의 대표 상품인 \'당당치킨\'이다. 현장의 델리 코너 직원은 "다른 제품은 만들어 진열해도 잘 나가지 않지만, 치킨은 찾는 손님이 꽤 있어서 요새는 치킨 한 종류에만 집중하고 있다"고 말했다. \n\n\n\n            15개의 계산대 중 1곳(9번)만 운영하는 모습./김수정 기자\n           \n\n ◆불 켜진 계산대는 단 1곳 \n총 15개에 달하는 메가푸드마켓의 계산대 중 실제로 불이 켜져 있고 직원이 상주하는 곳은 단 한 곳뿐이었다. 인건비를 줄이기 위해 대부분의 고객을 키오스크(셀프 계산대)로 유도하고 있었다. 이곳에서 오래 근무했다는 직원 C씨는 "예전에 비해 손님이 줄었다"며 "평일 낮에는 한산하지만 저녁이나 주말은 상황이 조금 낫다"고 전했다. 최근 언론을 통해 보도되는 \'6~7월 영업 정상화 가능성\'에 대해서는 "그런 이야기가 돌고 있다는 것은 들었다. 아직 지점 차원에서 확실하게 내려온 지침이나 계획은 없다"며 "상황이 조속히 좋아지기만을 바랄 뿐"이라고 말했다. \n건물 곳곳에 영업을 중단한 매장들도 있었다. 홈플러스 몰 1층 식당가 내부에 리뉴얼 준비 중인 매장 두 곳은 오픈 예정일이 언제인지조차 적혀 있지 않았다. \n\n\n\n            홈플러스몰 1층에 입점해 있는 의류 매장 모습./김수정 기자\n           \n\n ◆입점 업체, 매출 걱정에 시름 \n한때 대형마트의 큰 경쟁력이었던 \'원스톱\' 쇼핑 환경의 메리트도 사라졌다. 그간 홈플러스는 마트 내에 다양한 입점업체를 유치함으로써 집객 효과를 최대화 했다. 입점업체 또한 마트 고객을 점포에 유치함으로써 윈-윈(Win-Win) 효과를 얻었다. 홈플러스의 상황이 악화하면서 입점업체들 또한 큰 어려움에 빠졌다. \n홈플러스에 따르면 3000천여 곳의 입점 업체 중 60~70%가 소상공인이다. 이들은 지난해 3월 기업 회생 신청 이후 최소 20~30%까지 매출이 감소한 것으로 알려졌다. 마트의 경영난이 고스란히 입점 소상공인들의 생존 위기로 이어지는 악순환의 고리가 형성되며 소상공인들의 생계까지 영향을 주고 있다. \n\n\n\n            홈플러스 몰 내부 리뉴얼 준비 중인 매장. \'새로운 모습을 위한 준비 중입니다\'라는 문구의 가림막이 걸려 있다./김수정 기자\n           \n\n ◆여전히 자금난 \'안개 속\' \n홈플러스의 현장 정상화 노력 뒤에는 여전히 심각한 자금난이 자리하고 있다. 홈플러스는 지난달 7일 하림그룹 계열사 NS쇼핑과 슈퍼마켓 사업 부문인 홈플러스익스프레스를 1206억원에 매각하는 영업양도 계약을 체결했다. \n메리츠증권은 최근 입장문을 내고 "MBK는 메리츠에 추가 자금 지원을 요구하면서도 최대주주로서 최소한의 보증 제공은 거부하고 있다"며 MBK의 책임 있는 결단을 촉구했다. \n홈플러스 또한 메리츠증권을 향해 2000억원 규모 DIP의 신속한 집행을 거듭 요청했다. 홈플러스 측은 "회생에 필요한 유동성이 확보된다면 홈플러스는 충분히 정상화의 길로 나아갈 수 있다"고 주장했다. \n자금줄을 쥔 이해관계사들의 팽팽한 줄다리기 속에서 애가 타는 건 결국 현장의 직원과 고객이다. 당장 생계가 걸린 직원들의 고용 불안과 마트를 이용하던 소비자들의 불편이 언제쯤 해소될까.'}

In [111]:
print('제목:')
print(news['title'])

제목:
[르포] "채소 칸에 도마·국자라도"... 홈플러스의 처절한 빈자리 채우기

In [112]:
print('\n본문:')
print(news['content'])

본문:
경기도 파주에 위치한 홈플러스 매장의 외관./김수정 기자


 경기도 파주에 한 홈플러스 매장. 멀리서도 시계탑 달린 커다란 5층 건물이 한눈에 들어온다. 이 지점은 2016년 개점 당시, 지역 최대 규모의 복합 쇼핑몰이라는 점을 내세우며 화려하게 문을 열었다. 주말이면 가족 단위 방문객으로 인산인해를 이루며 지역 상권의 중심지 역할을 톡톡히 해왔다. 10년이 흐른 현재, 건물의 상징이었던 시계탑은 멈춰 섰고, 사람들의 발걸음도 현저히 줄었다.



            홈플러스 매장 1층 이벤트 매대 일부 공간이 텅 비어 있는 모습./김수정 기자


 지난 22일 오전 11시, 입구에 들어서자마자 1층 한 쪽 덩그러니 비어 있는 공간이 눈에 띄었다. '지금까지 없던 가장 현명한 선택'이라는 홈플러스의 슬로건이 무색하게, 현장에서 마주한 모습은 깊어지는 경영난을 고스란히 노출시켰다.



            신선 식품 코너에 국자, 도마 등 식기류가 진열된 모습./김수정 기자


 ◆상추·달걀 자리에 '냄비와 국자'
홈플러스가 오프라인 경쟁력 확보를 위해 사활을 걸고 추진해 온 '메가푸드마켓' 식품관. 신선도가 생명인 달걀, 채소, 샐러드 등이 진열되어 있어야 할 신선 코너 냉장 매대에 뜬금없이 주방용품과 국자, 도마 등 식기류들이 줄지어 진열돼 있었다. '텅 빈 매장'이라는 인상을 주지 않기 위해 매대를 채우려 애쓴 현장의 간절함과 처절함이 묻어났다. 인근에 거주한다는 방문객 A씨는 "한달만에 왔는데 신선실에 냄비와 국자가 진열된 것을 보고 깜짝 놀랐다"고 말했다.



            홈플러스 PB브랜드 'Simplus' 아메리카노가 매대 가득 진열된 모습./김수정 기자


 제품의 다양성도 크게 후퇴했다. 밀키트 코너는 홈플러스의 자체 브랜드(PB)인 '심플러스(simplus)'와 '홈밀(homemeal)' 제품으로만 빼곡했다. 음료 코너 냉장고에도 심플러스의 1000원 아메리카노와 복숭아 음료만 한 줄로 진열돼 있었다. 일반 라면 코너에는 특정 몇 가지 제품만 매대를 간신히 채우고 있었다. 30대 주부 B씨는 "집이 가까워 자주 왔었는데 요즘은 살 게 없어 발길이 뜸해졌다"며 "가격 메리트는 있지만, 구하기 힘든 상품도 아니고 '불닭볶음면' 같은 대중적인 라면조차 없다"고 아쉬워했다.



            홈플러스 메가푸드마켓 내 라면 코너의 모습./김수정 기자


 델리(즉석식품) 코너는 6990원 치킨만이 빈자리를 메우고 있었다. 홈플러스의 대표 상품인 '당당치킨'이다. 현장의 델리 코너 직원은 "다른 제품은 만들어 진열해도 잘 나가지 않지만, 치킨은 찾는 손님이 꽤 있어서 요새는 치킨 한 종류에만 집중하고 있다"고 말했다.



            15개의 계산대 중 1곳(9번)만 운영하는 모습./김수정 기자


 ◆불 켜진 계산대는 단 1곳
총 15개에 달하는 메가푸드마켓의 계산대 중 실제로 불이 켜져 있고 직원이 상주하는 곳은 단 한 곳뿐이었다. 인건비를 줄이기 위해 대부분의 고객을 키오스크(셀프 계산대)로 유도하고 있었다. 이곳에서 오래 근무했다는 직원 C씨는 "예전에 비해 손님이 줄었다"며 "평일 낮에는 한산하지만 저녁이나 주말은 상황이 조금 낫다"고 전했다. 최근 언론을 통해 보도되는 '6~7월 영업 정상화 가능성'에 대해서는 "그런 이야기가 돌고 있다는 것은 들었다. 아직 지점 차원에서 확실하게 내려온 지침이나 계획은 없다"며 "상황이 조속히 좋아지기만을 바랄 뿐"이라고 말했다.
건물 곳곳에 영업을 중단한 매장들도 있었다. 홈플러스 몰 1층 식당가 내부에 리뉴얼 준비 중인 매장 두 곳은 오픈 예정일이 언제인지조차 적혀 있지 않았다.



            홈플러스몰 1층에 입점해 있는 의류 매장 모습./김수정 기자


 ◆입점 업체, 매출 걱정에 시름
한때 대형마트의 큰 경쟁력이었던 '원스톱' 쇼핑 환경의 메리트도 사라졌다. 그간 홈플러스는 마트 내에 다양한 입점업체를 유치함으로써 집객 효과를 최대화 했다. 입점업체 또한 마트 고객을 점포에 유치함으로써 윈-윈(Win-Win) 효과를 얻었다. 홈플러스의 상황이 악화하면서 입점업체들 또한 큰 어려움에 빠졌다.
홈플러스에 따르면 3000천여 곳의 입점 업체 중 60~70%가 소상공인이다. 이들은 지난해 3월 기업 회생 신청 이후 최소 20~30%까지 매출이 감소한 것으로 알려졌다. 마트의 경영난이 고스란히 입점 소상공인들의 생존 위기로 이어지는 악순환의 고리가 형성되며 소상공인들의 생계까지 영향을 주고 있다.



            홈플러스 몰 내부 리뉴얼 준비 중인 매장. '새로운 모습을 위한 준비 중입니다'라는 문구의 가림막이 걸려 있다./김수정 기자


 ◆여전히 자금난 '안개 속'
홈플러스의 현장 정상화 노력 뒤에는 여전히 심각한 자금난이 자리하고 있다. 홈플러스는 지난달 7일 하림그룹 계열사 NS쇼핑과 슈퍼마켓 사업 부문인 홈플러스익스프레스를 1206억원에 매각하는 영업양도 계약을 체결했다.
메리츠증권은 최근 입장문을 내고 "MBK는 메리츠에 추가 자금 지원을 요구하면서도 최대주주로서 최소한의 보증 제공은 거부하고 있다"며 MBK의 책임 있는 결단을 촉구했다.
홈플러스 또한 메리츠증권을 향해 2000억원 규모 DIP의 신속한 집행을 거듭 요청했다. 홈플러스 측은 "회생에 필요한 유동성이 확보된다면 홈플러스는 충분히 정상화의 길로 나아갈 수 있다"고 주장했다.
자금줄을 쥔 이해관계사들의 팽팽한 줄다리기 속에서 애가 타는 건 결국 현장의 직원과 고객이다. 당장 생계가 걸린 직원들의 고용 불안과 마트를 이용하던 소비자들의 불편이 언제쯤 해소될까.

> 👉 headers는 웹 브라우저가 서버에 보내는 추가 정보이며, 크롤링에서는 서버가 요청을 정상적인 브라우저 접속으로 인식하도록 도와주는 역할을 합니다. User-Agent는 “어떤 브라우저와 운영체제로 접속했는가”를 나타내는 정보로, 이를 설정하지 않으면 일부 사이트는 프로그램(봇) 접속으로 판단하여 데이터를 차단하거나 빈 페이지를 반환할 수 있습니다. Referer는 “어떤 페이지에서 이동해 왔는가”를 나타내는 정보이며, 벅스 같은 사이트는 내부 페이지 이동처럼 보여야 정상 응답을 주는 경우가 있어 함께 설정하는 경우가 많습니다. 즉, headers는 크롤링 프로그램이 실제 사람이 사용하는 브라우저처럼 보이게 만들어 사이트 차단을 줄이고 안정적으로 데이터를 가져오기 위해 사용하는 중요한 설정입니다.

# robots.txt
robots.txt는 웹사이트 운영자가 검색 엔진이나 크롤링 프로그램(봇)에게 “어떤 페이지는 접근 가능하고, 어떤 페이지는 접근하지 말아야 하는지”를 알려주는 규칙 파일입니다. 보통 사이트 주소 뒤에 /robots.txt를 붙여 확인할 수 있으며, 예를 들어 https://example.com/robots.txt 형태로 접근합니다. 이 파일에는 특정 경로를 수집 금지(Disallow) 하거나 허용(Allow) 하는 규칙이 작성되어 있으며, 검색 엔진이나 크롤러는 이를 참고하여 사이트에 과도한 부하를 주지 않고 운영 정책을 존중하며 데이터를 수집합니다. 다만 robots.txt는 강제 차단 시스템이 아니라 “권장 규칙”에 가까우므로 기술적으로 접근은 가능할 수 있지만, 실무에서는 반드시 robots.txt와 사이트 이용약관을 확인하고 서버에 무리를 주지 않는 범위에서 크롤링하는 것이 중요합니다.

# 벅스 아티스트 곡 리스트 크롤링

In [128]:
def bugs_artist_tracks(artist_id):
    url = f"https://music.bugs.co.kr/artist/{artist_id}/tracks"
    
    headers = {
        "User-Agent": "Mozilla/5.0",
        "Referer": "https://music.bugs.co.kr/"
    }

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    # response.raise_for_status()

    rows = soup.select("table.list.trackList tbody tr")

    data = []

    for row in rows:
        title_tag = row.select_one("p.title a")
        artist_tag = row.select_one("p.artist a")
        album_tag = row.select_one("a.album")

        if not title_tag:
            continue

        title = title_tag.get_text(strip=True)
        artist =artist_tag.get_text(strip=True) if artist_tag else ""
        album = album_tag.get_text(strip=True) if album_tag else ""

        data.append({
                "곡명": title,
                "아티스트": artist,
                "앨범명": album
        })
    
    df = pd.DataFrame(data)
    df.index = df.index + 1

    file_name = f"bugs_artist_{artist_id}_tracks.csv"
    df.to_csv(file_name, encoding="utf-8-sig")

    return df

In [ ]:
df = bugs_artist_tracks("20260859")
df

                  곡명  아티스트              앨범명
1  이젠 내가 더 사랑해 (PJ2)  신의키스  The Bucket List
2            너 없는 생일  신의키스  The Bucket List
3      서로를 가장 잘 아는 남  신의키스  The Bucket List
4             헤어질 준비  신의키스  The Bucket List
5  이젠 내가 더 사랑해 (PJ1)  신의키스  The Bucket List
6             버킷 리스트  신의키스  The Bucket List

In [126]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time


def bugs_artist_tracks_all_pages(artist_id, max_page=20):
    headers = {
        "User-Agent": "Mozilla/5.0",
        "Referer": "https://music.bugs.co.kr/"
    }

    all_data = []

    for page in range(1, max_page + 1):
        url = (
            f"https://music.bugs.co.kr/artist/{artist_id}/tracks"
            f"?type=RELEASE&sort=P&page={page}&roleCode=0&highQualityOnly="
        )

        response = requests.get(url, headers=headers)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, "html.parser")

        rows = soup.select("table.trackList tbody tr")

        page_data = []

        for row in rows:
            title_tag = row.select_one("p.title a")
            artist_tag = row.select_one("p.artist a")
            album_tag = row.select_one("a.album")

            if title_tag is None:
                continue

            page_data.append({
                "곡명": title_tag.get_text(strip=True),
                "아티스트": artist_tag.get_text(strip=True) if artist_tag else "",
                "앨범명": album_tag.get_text(strip=True) if album_tag else "",
                "페이지": page
            })

        if len(page_data) == 0:
            print(f"{page}페이지에 곡이 없어 종료합니다.")
            break

        all_data.extend(page_data)
        print(f"{page}페이지 크롤링 완료: {len(page_data)}곡")

        time.sleep(0.5)

    df = pd.DataFrame(all_data)

    if not df.empty:
        df = df.drop_duplicates(subset=["곡명", "아티스트", "앨범명"])
        df.index = df.index + 1

    file_name = f"bugs_artist_{artist_id}_tracks.csv"
    df.to_csv(file_name, encoding="utf-8-sig")

    print(f"CSV 저장 완료: {file_name}")
    print(f"총 {len(df)}곡 수집 완료")

    return df

In [127]:
df = bugs_artist_tracks_all_pages("20260859")
df

1페이지 크롤링 완료: 6곡
2페이지에 곡이 없어 종료합니다.
CSV 저장 완료: bugs_artist_20260859_tracks.csv
총 6곡 수집 완료

                  곡명  아티스트              앨범명  페이지
1  이젠 내가 더 사랑해 (PJ2)  신의키스  The Bucket List    1
2            너 없는 생일  신의키스  The Bucket List    1
3      서로를 가장 잘 아는 남  신의키스  The Bucket List    1
4             헤어질 준비  신의키스  The Bucket List    1
5  이젠 내가 더 사랑해 (PJ1)  신의키스  The Bucket List    1
6             버킷 리스트  신의키스  The Bucket List    1