In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 좋아요 수 안 나옴

In [43]:
def melon_artist_tracks_all_pages():
    headers = {
        "User-Agent": "Mozilla/5.0",
        "Referer": "https://www.melon.com/index.htm"
    }

    all_data = []

    
    url = (
        f"https://www.melon.com/chart/index.htm"
    )
    response = requests.get(url, headers=headers)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    rows= soup.select("tbody tr")

    # print(len(rows)) # 가져오는지 증명
    
    page_data = []

    for row in rows:
        rank_tag = row.select_one("span.rank")
        title_tag = row.select_one("div.rank01 a")
        artist_tag = row.select_one("div.rank02 a")
        album_tag = row.select_one("div.rank03 a")
        like_tag = row.select_one("span.cnt")

        print(repr(like_tag.get_text(strip=True)))
        
        if title_tag is None:
            continue

        
        page_data.append({
            "순위": rank_tag.get_text(strip=True),
            "곡명": title_tag.get_text(strip=True),
            "아티스트": artist_tag.get_text(strip=True) if artist_tag else "",
            "앨범명": album_tag.get_text(strip=True) if album_tag else "",
            "좋아요 수": like_tag.get_text(strip=True).replace("총건수", "") if like_tag else ""
        })

        if len(page_data) == 0:
            # print(f"{page}100곡 끝 일단해")
            break
        
        
        print(f"크롤링 완료: {len(page_data)}곡")
    all_data.extend(page_data)
    df = pd.DataFrame(all_data)

    if not df.empty:
        df = df.drop_duplicates(subset=["순위", "곡명", "아티스트", "앨범명", "좋아요 수"])
        # df.index = df.index + 1

    file_name = f"melon_top100_tracks.csv"
    df.to_csv(file_name, encoding="utf-8-sig", index =False)

    print(f"CSV 저장 완료: {file_name}")
    print(f"총 {len(df)}곡 수집 완료")

    return df

In [44]:
df = melon_artist_tracks_all_pages()
df

'총건수0'
크롤링 완료: 1곡
'총건수0'
크롤링 완료: 2곡
'총건수0'
크롤링 완료: 3곡
'총건수0'
크롤링 완료: 4곡
'총건수0'
크롤링 완료: 5곡
'총건수0'
크롤링 완료: 6곡
'총건수0'
크롤링 완료: 7곡
'총건수0'
크롤링 완료: 8곡
'총건수0'
크롤링 완료: 9곡
'총건수0'
크롤링 완료: 10곡
'총건수0'
크롤링 완료: 11곡
'총건수0'
크롤링 완료: 12곡
'총건수0'
크롤링 완료: 13곡
'총건수0'
크롤링 완료: 14곡
'총건수0'
크롤링 완료: 15곡
'총건수0'
크롤링 완료: 16곡
'총건수0'
크롤링 완료: 17곡
'총건수0'
크롤링 완료: 18곡
'총건수0'
크롤링 완료: 19곡
'총건수0'
크롤링 완료: 20곡
'총건수0'
크롤링 완료: 21곡
'총건수0'
크롤링 완료: 22곡
'총건수0'
크롤링 완료: 23곡
'총건수0'
크롤링 완료: 24곡
'총건수0'
크롤링 완료: 25곡
'총건수0'
크롤링 완료: 26곡
'총건수0'
크롤링 완료: 27곡
'총건수0'
크롤링 완료: 28곡
'총건수0'
크롤링 완료: 29곡
'총건수0'
크롤링 완료: 30곡
'총건수0'
크롤링 완료: 31곡
'총건수0'
크롤링 완료: 32곡
'총건수0'
크롤링 완료: 33곡
'총건수0'
크롤링 완료: 34곡
'총건수0'
크롤링 완료: 35곡
'총건수0'
크롤링 완료: 36곡
'총건수0'
크롤링 완료: 37곡
'총건수0'
크롤링 완료: 38곡
'총건수0'
크롤링 완료: 39곡
'총건수0'
크롤링 완료: 40곡
'총건수0'
크롤링 완료: 41곡
'총건수0'
크롤링 완료: 42곡
'총건수0'
크롤링 완료: 43곡
'총건수0'
크롤링 완료: 44곡
'총건수0'
크롤링 완료: 45곡
'총건수0'
크롤링 완료: 46곡
'총건수0'
크롤링 완료: 47곡
'총건수0'
크롤링 완료: 48곡
'총건수0'
크롤링 완료: 49곡
'총건수0'
크롤링 완료: 50곡
'총건수0'
크롤링 완료: 51곡
'총건수0'
크롤링 완료: 52곡
'총건수0'
크롤링 완료: 53곡
'총건수0'
크롤링 완료: 54곡
'총건수0'
크롤링 완료: 55곡
'총건수0'
크롤링 완료: 56곡
'총건수0'
크롤링 완료: 57곡
'총건수0'
크롤링 완료: 58곡
'총건수0'
크롤링 완료: 59곡
'총건수0'
크롤링 완료: 60곡
'총건수0'
크롤링 완료: 61곡
'총건수0'
크롤링 완료: 62곡
'총건수0'
크롤링 완료: 63곡
'총건수0'
크롤링 완료: 64곡
'총건수0'
크롤링 완료: 65곡
'총건수0'
크롤링 완료: 66곡
'총건수0'
크롤링 완료: 67곡
'총건수0'
크롤링 완료: 68곡
'총건수0'
크롤링 완료: 69곡
'총건수0'
크롤링 완료: 70곡
'총건수0'
크롤링 완료: 71곡
'총건수0'
크롤링 완료: 72곡
'총건수0'
크롤링 완료: 73곡
'총건수0'
크롤링 완료: 74곡
'총건수0'
크롤링 완료: 75곡
'총건수0'
크롤링 완료: 76곡
'총건수0'
크롤링 완료: 77곡
'총건수0'
크롤링 완료: 78곡
'총건수0'
크롤링 완료: 79곡
'총건수0'
크롤링 완료: 80곡
'총건수0'
크롤링 완료: 81곡
'총건수0'
크롤링 완료: 82곡
'총건수0'
크롤링 완료: 83곡
'총건수0'
크롤링 완료: 84곡
'총건수0'
크롤링 완료: 85곡
'총건수0'
크롤링 완료: 86곡
'총건수0'
크롤링 완료: 87곡
'총건수0'
크롤링 완료: 88곡
'총건수0'
크롤링 완료: 89곡
'총건수0'
크롤링 완료: 90곡
'총건수0'
크롤링 완료: 91곡
'총건수0'
크롤링 완료: 92곡
'총건수0'
크롤링 완료: 93곡
'총건수0'
크롤링 완료: 94곡
'총건수0'
크롤링 완료: 95곡
'총건수0'
크롤링 완료: 96곡
'총건수0'
크롤링 완료: 97곡
'총건수0'
크롤링 완료: 98곡
'총건수0'
크롤링 완료: 99곡
'총건수0'
크롤링 완료: 100곡
CSV 저장 완료: melon_top100_tracks.csv
총 100곡 수집 완료

,순위,곡명,아티스트,앨범명,좋아요 수
0,1,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],0
1,2,REDRED,CORTIS (코르티스),GREENGREEN,0
2,3,LEMONADE,aespa,LEMONADE - The 2nd Album,0
3,4,It′s Me,아일릿(ILLIT),MAMIHLAPINATAPAI,0
4,5,LOVE ATTACK,RESCENE (리센느),SCENEDROME,0
...,...,...,...,...,...
95,96,에피소드,이무진,에피소드,0
96,97,OVERDRIVE,TWS (투어스),play hard,0
97,98,KISS KISS KISS (Feat. 선우 (THE BOYZ)) (Prod. by...,NOWIMYOUNG (나우아임영),쇼미더머니 12 Episode 2,0
98,99,D-D-Done,RIIZE,II - The 2nd Mini Album,0
99,100,Flashback,엔플라잉 (N.Flying),Man on the Moon,0

# 제미나이 도움으로 좋아요 수 나옴

In [ ]:
# import requests
# from bs4 import BeautifulSoup
# import pandas as pd

# def melon_top100_crawler():
#     # 1. 멜론 봇 차단을 막기 위한 크롬 브라우저 위장 헤더
#     headers = {
#         "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
#         "Referer": "https://www.melon.com/index.htm"
#     }

#     all_data = []
#     url = "https://www.melon.com/chart/index.htm"
    
#     response = requests.get(url, headers=headers)
#     response.raise_for_status()

#     soup = BeautifulSoup(response.text, "html.parser")
#     rows = soup.select("tbody tr")
    
#     page_data = []
#     song_ids = [] # 곡 고유 ID들을 모아둘 빈 바구니

#     # 2. 100곡의 기본 정보와 '곡 ID' 추출하기
#     for row in rows:
#         rank_tag = row.select_one("span.rank")
#         title_tag = row.select_one("div.rank01 a")
#         artist_tag = row.select_one("div.rank02 a")
#         album_tag = row.select_one("div.rank03 a")
        
#         # 텍스트가 아니라 <button> 태그의 속성에서 곡 ID를 뽑아냅니다.
#         like_btn = row.select_one("button.like") 
#         song_id = like_btn["data-song-no"] if like_btn else ""
        
#         if title_tag is None:
#             continue

#         # 뽑아낸 곡 ID를 바구니에 담습니다.
#         if song_id:
#             song_ids.append(song_id)

#         page_data.append({
#             "순위": rank_tag.get_text(strip=True),
#             "곡명": title_tag.get_text(strip=True),
#             "아티스트": artist_tag.get_text(strip=True) if artist_tag else "",
#             "앨범명": album_tag.get_text(strip=True) if album_tag else "",
#             "곡 ID": song_id,  # 나중에 좋아요 수랑 짝지어주기 위한 열쇠
#             "좋아요 수": 0     # 빈칸 대신 일단 0으로 둡니다.
#         })

#     all_data.extend(page_data)
    
#     # 3. 모아둔 ID로 멜론 API를 찔러서 진짜 좋아요 수 100개 한 번에 가져오기
#     if song_ids:
#         # ID들을 콤마로 이어 붙입니다. (예: "602024048,1000002721...")
#         ids_param = ",".join(song_ids)
        
#         # [핵심] 에러가 나지 않는 진짜 JSON API 주소입니다.
#         like_url = f"https://www.melon.com/commonlike/getSongLike.json?contsIds={ids_param}"
        
#         # 멜론 API에 요청해서 정답 데이터를 받습니다.
#         like_response = requests.get(like_url, headers=headers)
#         like_json = like_response.json()
        
#         # [핵심] 대문자 키값(CONTSID, SUMMCNT)을 사용하여 딕셔너리를 만듭니다.
#         like_dict = {str(item["CONTSID"]): item["SUMMCNT"] for item in like_json["contsLike"]}
        
#         # 아까 만든 all_data에 진짜 좋아요 수를 끼워 넣습니다.
#         for song in all_data:
#             s_id = song["곡 ID"]
#             if s_id in like_dict:
#                 song["좋아요 수"] = f"{like_dict[s_id]:,}" # 천 단위 콤마(,) 찍어서 깔끔하게 저장
#             del song["곡 ID"] # 엑셀에 ID 열은 필요 없으니 여기서 삭제합니다.

#     # 4. 데이터프레임으로 만들고 CSV 파일로 저장하기
#     df = pd.DataFrame(all_data)

#     if not df.empty:
#         df = df.drop_duplicates(subset=["순위", "곡명", "아티스트", "앨범명", "좋아요 수"])

#     # index=False 옵션으로 불필요한 행 번호(0,1,2...)가 생기는 것을 막습니다.
#     file_name = "melon_top100_tracks.csv"
#     df.to_csv(file_name, encoding="utf-8-sig", index=False)

#     print(f"CSV 저장 완료: {file_name}")
#     print(f"총 {len(df)}곡 수집 완료 (진짜 좋아요 데이터 포함!)")

#     return df

# # 함수 실행 (이 줄이 있어야 코드가 작동합니다!)
# melon_top100_crawler()

CSV 저장 완료: melon_top100_tracks.csv
총 100곡 수집 완료 (진짜 좋아요 데이터 포함!)

,순위,곡명,아티스트,앨범명,좋아요 수
0,1,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],"56,388"
1,2,REDRED,CORTIS (코르티스),GREENGREEN,"65,269"
2,3,LEMONADE,aespa,LEMONADE - The 2nd Album,"40,295"
3,4,It′s Me,아일릿(ILLIT),MAMIHLAPINATAPAI,"43,712"
4,5,LOVE ATTACK,RESCENE (리센느),SCENEDROME,"84,864"
...,...,...,...,...,...
95,96,에피소드,이무진,에피소드,"143,536"
96,97,OVERDRIVE,TWS (투어스),play hard,"45,549"
97,98,KISS KISS KISS (Feat. 선우 (THE BOYZ)) (Prod. by...,NOWIMYOUNG (나우아임영),쇼미더머니 12 Episode 2,"33,131"
98,99,D-D-Done,RIIZE,II - The 2nd Mini Album,"14,004"
99,100,Flashback,엔플라잉 (N.Flying),Man on the Moon,"60,301"

# 또 다른 방법

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

def melon_artist_tracks_all_pages():
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        "Referer": "https://www.melon.com/index.htm"
    }

    all_data = []

    url = f"https://www.melon.com/chart/index.htm"
    response = requests.get(url, headers=headers)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")
    rows = soup.select("tbody tr")

    # =========================================================
    # [추가된 API 로직] 반복문을 돌기 전에 미리 100곡의 정답지를 받아옵니다.
    song_ids = [row.select_one("button.like")['data-song-no'] for row in rows if row.select_one("button.like")]
    like_api_url = f"https://www.melon.com/commonlike/getSongLike.json?contsIds={','.join(song_ids)}"
    like_data = requests.get(like_api_url, headers=headers).json()
    # =========================================================

    page_data = []

    # [수정된 부분] zip을 써서 HTML(row)과 정답지(like)를 동시에 꺼냅니다.
    for row, like in zip(rows, like_data['contsLike']):
        rank_tag = row.select_one("span.rank")
        title_tag = row.select_one("div.rank01 a")
        artist_tag = row.select_one("div.rank02 a")
        album_tag = row.select_one("div.rank03 a")

        if title_tag is None:
            continue

        page_data.append({
            "순위": rank_tag.get_text(strip=True),
            "곡명": title_tag.get_text(strip=True),
            "아티스트": artist_tag.get_text(strip=True) if artist_tag else "",
            "앨범명": album_tag.get_text(strip=True) if album_tag else "",
            "좋아요 수": f"{like['SUMMCNT']:,}" # 가짜 0 대신 진짜 좋아요 숫자를 넣습니다!
        })

        if len(page_data) == 0:
            break
        
        print(f"크롤링 진행 중: {len(page_data)}곡")

    all_data.extend(page_data)
    df = pd.DataFrame(all_data)

    if not df.empty:
        df = df.drop_duplicates(subset=["순위", "곡명", "아티스트", "앨범명", "좋아요 수"])

    file_name = f"melon_top100_tracks.csv"
    df.to_csv(file_name, encoding="utf-8-sig", index=False)

    print(f"CSV 저장 완료: {file_name}")
    print(f"총 {len(df)}곡 수집 완료")

    return df

melon_artist_tracks_all_pages()

크롤링 진행 중: 1곡
크롤링 진행 중: 2곡
크롤링 진행 중: 3곡
크롤링 진행 중: 4곡
크롤링 진행 중: 5곡
크롤링 진행 중: 6곡
크롤링 진행 중: 7곡
크롤링 진행 중: 8곡
크롤링 진행 중: 9곡
크롤링 진행 중: 10곡
크롤링 진행 중: 11곡
크롤링 진행 중: 12곡
크롤링 진행 중: 13곡
크롤링 진행 중: 14곡
크롤링 진행 중: 15곡
크롤링 진행 중: 16곡
크롤링 진행 중: 17곡
크롤링 진행 중: 18곡
크롤링 진행 중: 19곡
크롤링 진행 중: 20곡
크롤링 진행 중: 21곡
크롤링 진행 중: 22곡
크롤링 진행 중: 23곡
크롤링 진행 중: 24곡
크롤링 진행 중: 25곡
크롤링 진행 중: 26곡
크롤링 진행 중: 27곡
크롤링 진행 중: 28곡
크롤링 진행 중: 29곡
크롤링 진행 중: 30곡
크롤링 진행 중: 31곡
크롤링 진행 중: 32곡
크롤링 진행 중: 33곡
크롤링 진행 중: 34곡
크롤링 진행 중: 35곡
크롤링 진행 중: 36곡
크롤링 진행 중: 37곡
크롤링 진행 중: 38곡
크롤링 진행 중: 39곡
크롤링 진행 중: 40곡
크롤링 진행 중: 41곡
크롤링 진행 중: 42곡
크롤링 진행 중: 43곡
크롤링 진행 중: 44곡
크롤링 진행 중: 45곡
크롤링 진행 중: 46곡
크롤링 진행 중: 47곡
크롤링 진행 중: 48곡
크롤링 진행 중: 49곡
크롤링 진행 중: 50곡
크롤링 진행 중: 51곡
크롤링 진행 중: 52곡
크롤링 진행 중: 53곡
크롤링 진행 중: 54곡
크롤링 진행 중: 55곡
크롤링 진행 중: 56곡
크롤링 진행 중: 57곡
크롤링 진행 중: 58곡
크롤링 진행 중: 59곡
크롤링 진행 중: 60곡
크롤링 진행 중: 61곡
크롤링 진행 중: 62곡
크롤링 진행 중: 63곡
크롤링 진행 중: 64곡
크롤링 진행 중: 65곡
크롤링 진행 중: 66곡
크롤링 진행 중: 67곡
크롤링 진행 중: 68곡
크롤링 진행 중: 69곡
크롤링 진행 중: 70곡
크롤링 진행 중: 71곡
크롤링 진행 중: 72곡
크롤링 진행 중: 73곡
크롤링 진행 중: 74곡
크롤링 진행 중: 75곡
크롤링 진행 중: 76곡
크롤링 진행 중: 77곡
크롤링 진행 중: 78곡
크롤링 진행 중: 79곡
크롤링 진행 중: 80곡
크롤링 진행 중: 81곡
크롤링 진행 중: 82곡
크롤링 진행 중: 83곡
크롤링 진행 중: 84곡
크롤링 진행 중: 85곡
크롤링 진행 중: 86곡
크롤링 진행 중: 87곡
크롤링 진행 중: 88곡
크롤링 진행 중: 89곡
크롤링 진행 중: 90곡
크롤링 진행 중: 91곡
크롤링 진행 중: 92곡
크롤링 진행 중: 93곡
크롤링 진행 중: 94곡
크롤링 진행 중: 95곡
크롤링 진행 중: 96곡
크롤링 진행 중: 97곡
크롤링 진행 중: 98곡
크롤링 진행 중: 99곡
크롤링 진행 중: 100곡
CSV 저장 완료: melon_top100_tracks.csv
총 100곡 수집 완료

,순위,곡명,아티스트,앨범명,좋아요 수
0,1,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],"56,401"
1,2,REDRED,CORTIS (코르티스),GREENGREEN,"65,279"
2,3,LEMONADE,aespa,LEMONADE - The 2nd Album,"40,306"
3,4,It′s Me,아일릿(ILLIT),MAMIHLAPINATAPAI,"43,715"
4,5,LOVE ATTACK,RESCENE (리센느),SCENEDROME,"84,888"
...,...,...,...,...,...
95,96,달리 표현할 수 없어요,로이킴,달리 표현할 수 없어요,"43,001"
96,97,BLACKHOLE,IVE (아이브),REVIVE+,"40,462"
97,98,우리들의 블루스,임영웅,IM HERO,"125,771"
98,99,ONE MORE TIME,ALLDAY PROJECT,ALLDAY PROJECT,"62,186"
99,100,"TICK TOCK (Feat. ZICO) (Prod. by ZICO, Crush)",김하온 (HAON),쇼미더머니 12 Episode 1,"41,723"